### ISSUE TITLE
What about a newer version based on eez-open? Firmware with SCPI support and other things

### ISSUE THREAD

**Issue by timofonic** [thebiguno/microcontroller-projects#1]
@eez-open did a very nice work. I miss the project would be in KiCad, but he made a very interesting firmware with great SCPI support. There's a giant log about the process in both EEvBLOG and his webpage

https://github.com/eez-open
http://www.envox.hr/eez/bench-power-supply/psu-introduction.html

**Comment by thebiguno** [comment]
Looks nice, but I am not interested in changing the firmware at this point, as it already does exactly what I want.  Thanks for the suggestion, though!

Cheers
